### ISSUE TITLE
High Score Log

### ISSUE THREAD

**Issue by n-bakken** [n-bakken/final-project-group-3-near#2]
I think it would be fun to have a leaderboard of high scores, which shows the top five highest scores since the game has been run. I don't think I can make it remember the scores after I close the game, so I will be aiming for top five recent scores. 
It would be best to make a new menu button for this feature, so the user can pause and return to the menu to check the top scores and then return to their game. I'll need to change mainApplication to include a function to switch to a new screen. I'll also need to change MenuPane to include a new button to navigate to the new screen. 
I will make a new class to handle this feature, called ScorePane. It will be similar to SomePane in that it won't be super interactive, but it will show a list of the most recent high scores. If a user beats the highest score, it will immediately update. It will need a function to show the information, and a button and a function to navigate back to the main menu. 
If possible, I think it would be fun to input your name if you beat a high score, which can be shown with your score on the leaderboard. I will need to update Game Pane with a new function to handle this data, and I'll probably store the information in an arraylist so I can sort it easily.

**Comment by onzfonz** [comment]
You'll be able to save the new scores into a file that you can access.  I think I like this one the best.
